---
driver:
  name: vagrant

provisioner:
  name: chef_zero
#  data_bags_path: ./test/fixtures/data_bags

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
     - recipe[jmeter-ant::default]
    attributes:
